# Generated by Django 3.1.6 on 2021-04-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('fuelcap', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('topspeed', models.IntegerField()),
                ('bikeimg', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
