# Generated by Django 3.1.6 on 2021-04-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='costperday',
            field=models.IntegerField(default=100),
        ),
    ]
