# Generated by Django 3.1.6 on 2021-04-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
